base: 'https://ispm-typo3-v13.4.ddev.site/Chiffre'
dependencies:
  - bootstrap-package/full
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 6
websiteTitle: Chiffre
